version: '{branch}-build{build}'
image: Ubuntu1804

skip_commits:
  files:
  - '**/*.md'

build_script:
  - sh: dotnet build -c Release

after_build:
  - sh: chmod +x pack.sh && ./pack.sh

artifacts:
  - path: '**/artifacts/nuget/*.nupkg'
    name: NuGet
  - path: '**/artifacts/myget/*.nupkg'
    name: MyGet
    
deploy:
  - provider: NuGet
    api_key:
      secure: nts+1V9NzzFZbyAVeJs951l/7K01aEfLTEGGyb8t2zNMcZhBnlSTGPoQV8IRpsMa
    artifact: NuGet
    on:
      APPVEYOR_REPO_TAG: true
  - provider: NuGet
      server: https://www.myget.org/F/prometheus-client-net/api/v2/package
      api_key:
        secure: DvXZQgy0wcMjR87Zt1qBB9YaDmEiAAiylRxVFfnvkYmfD+oYUetgCi1B036DJZGF
      symbol_server: https://www.myget.org/F/prometheus-client-net/symbols/api/v2/package
      artifact: MyGet
      on:
        branch: master
        APPVEYOR_REPO_TAG: false    
