name: CI Production

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
      - name: Build
        run: dotnet build -c Release
      - name: Pack artifacts
        run: dotnet pack src/Prometheus.Client.AspNetCore -c Release --no-build -o artifacts/
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nupkg
          path: artifacts/*
      - name: Publish to NuGet
        run: dotnet nuget push "artifacts/*.nupkg" -k ${{ secrets.NUGET_DEPLOY_KEY }} -s https://api.nuget.org/v3/index.json
